version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    ports:
      - 5678:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres